### ISSUE TITLE
kernel does not boot

### ISSUE THREAD

**Issue by cloc3** [patrykk/linux-udoo#1]
starting from a working official ubuntu udoo-quad box, changing only the uImage, this kernel hungs on boot.
here the serial monitor:

cloc3 ~ # cu udoo
Connected.

U-Boot 2013.10-rc3 (Jan 20 2014 - 13:33:34)

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: UDOO
DRAM:  1 GiB
MMC:   FSL_SDHC: 0
No panel detected: default to LDB-WVGA
Display: LDB-WVGA (800x480)
In:    serial
Out:   serial
Err:   serial
Net:   using phy at 6
FEC [PRIME]
Hit any key to stop autoboot:  0
AHCI 0001.0300 32 slots 1 ports 3 Gbps 0x1 impl SATA mode
flags: ncq stag pm led clo only pmp pio slum part
No port device detected!
sata - SATA sub system

Usage:
sata init - init SATA sub system
sata info - show available SATA devices
sata device [dev] - show or set current device
sata part [dev] - print partition table
sata read addr blk# cnt
sata write addr blk# cnt
AHCI 0001.0300 32 slots 1 ports 3 Gbps 0x1 impl SATA mode
flags: ncq stag pm led clo only pmp pio slum part
No port device detected!
sata - SATA sub system

Usage:
sata init - init SATA sub system
sata info - show available SATA devices
sata device [dev] - show or set current device
sata part [dev] - print partition table
sata read addr blk# cnt
sata write addr blk# cnt
Booting from mmc ...
5600000 bytes read in 392 ms (13.6 MiB/s)
## Booting kernel from Legacy Image at 12000000 ...

   Image Name:   Linux-3.17.7-gb211594-dirty
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5599936 Bytes = 5.3 MiB
   Load Address: 10008000
   Entry Point:  10008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK

Starting kernel ...

**Comment by patrykk** [comment]
Please supply your uboot configuration and update uboot to 2014.04 version.

**Comment by cloc3** [comment]
sorry, patrykk,  if I continue my issue, even if my question may it be OT here.
Unlikely, I've requested a registration to udoo forum, but I've not received
it, whitout a particolar reason. So, I don't know how to manage my starting
problems with udoo.
Even I found on a lot of places, I've not understood the correct way to
configure u-boot for udoo (the last step of your README.md).

May you please give me some hint or some good reference?
That's my serial output after flashing udoo with a new u-boot, built from
git.denx.de/u-boot.git, checkout v2014.07:

cloc3 ~ # cu udoo
Connected.

U-Boot 2014.07-dirty (Jan 04 2015 - 23:12:50)

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: Udoo
DRAM:  1 GiB
MMC:   FSL_SDHC: 0
In:    serial
Out:   serial
Err:   serial
Net:   using phy at 6
FEC [PRIME]
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
Checking for: /uEnv.txt ...
Checking for: /boot/uEnv.txt ...
*\* Invalid partition 2 **
*\* Invalid partition 3 **
*\* Invalid partition 4 **
*\* Invalid partition 5 **
*\* Invalid partition 6 **
*\* Invalid partition 7 **
=> load
  load loadb loads loadx loady
=> load mmc 0 ${loadaddr} /boot/uImage
5262616 bytes read in 343 ms (14.6 MiB/s)
=> bootm

## Booting kernel from Legacy Image at 12000000 ...

   Image Name:   Linux-3.17.7-udoo-gb211594-dirty
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5262552 Bytes = 5 MiB
   Load Address: 10008000
   Entry Point:  10008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK

Starting kernel ...

**Comment by cloc3** [comment]
I found a working configuration (I don't know if it's the better, but it works for me).
instead of uImage, I put in /boot directory a kernel in this way:

$ uname_r=3.17.7-udoo-gb211594-dirty # udoo is from my CONFIG_LOCALVERSION
$ cp arch/arm/boot/Image /mnt/mySdCard/boot/vmlinuz-${uname_r}
$ cat >/mnt/mySdCard/boot/uEnv.txt <<-EOF

> uname_r=3.17.7-udoo-gb211594-dirty
> console=/dev/ttymxc1, 115200
> mmc_root=/dev/mmcblk0p1
> EOF

and that's all folk's ;)

**Comment by patrykk** [comment]
You must put your kernel and dtb file on SD card or run "load sata ..." for sata disks.

**Comment by cloc3** [comment]
thanks. my problem was not boot from sata, but from mmc only.
now, I'm realizing that my previuos solution, which comes following this howto: https://www.eewiki.net/pages/viewpage.action?pageId=35848524#UDOO-Bootloader:U-Boot, depends from the patch suggested there.
it works for me, even I've again problems with the standard u-boot from git://git.denx.de/u-boot.git.
now I hope udoo forum wranglers send me my registration to theyr forum, so I can ask for my problems in the right place :).
