### ISSUE TITLE
GPIO Output

### ISSUE THREAD

**Issue by gicardous** [patrykk/linux-udoo#16]
Hi,
please verify this:
echo 126 > export
echo out > /sys/class/gpio/gpio126/direction
echo 1 > /sys/class/gpio/gpio126/value
cat /sys/class/gpio/gpio126/value
echo 127 > export
echo out > /sys/class/gpio/gpio127/direction
echo 1 > /sys/class/gpio/gpio127/value
cat /sys/class/gpio/gpio127/value
Results from the above commands are always 0. Same issue with gpio 133,134,54 which are not assigned to other functions according to schematics.
Those pins are not electrically connected yet to anything.

**Comment by patrykk** [comment]
I dont understand where is the problem.

**Comment by patrykk** [comment]
Please check it:

echo out > direction 
[root@h4 gpio127]# cat value 
0
[root@h4 gpio127]# echo 0 > active_low 
[root@h4 gpio127]# cat value 
0
[root@h4 gpio127]# echo 1 > active_low 
[root@h4 gpio127]# cat value 
1

If it not worki like you want please try revert gpio polarization commit and supply some feedback.

**Comment by gicardous** [comment]
root@bastus:/sys/class/gpio/gpio127# echo out > direction
root@bastus:/sys/class/gpio/gpio127# cat value
0
root@bastus:/sys/class/gpio/gpio127# echo 0 > active_low
root@bastus:/sys/class/gpio/gpio127# cat value
0
root@bastus:/sys/class/gpio/gpio127# echo 1 > active_low
root@bastus:/sys/class/gpio/gpio127# cat value
1
root@bastus:/sys/class/gpio/gpio127# echo 0 > value
root@bastus:/sys/class/gpio/gpio127# cat value
1
As you see is working but i need to change the 'value' not 'active low'.

It works like that on a respberry pi:

root@yo4:/sys/class/gpio/gpio21# echo out > direction
root@yo4:/sys/class/gpio/gpio21# cat value
0
root@yo4:/sys/class/gpio/gpio21# echo 0 > active_low
root@yo4:/sys/class/gpio/gpio21# cat value
0
root@yo4:/sys/class/gpio/gpio21# echo 1 > active_low
root@yo4:/sys/class/gpio/gpio21# cat value
1
root@yo4:/sys/class/gpio/gpio21# echo 0 > value
root@yo4:/sys/class/gpio/gpio21# cat value
0
root@yo4:/sys/class/gpio/gpio21#

**Comment by patrykk** [comment]
Do you have some patches on RPi ? Could you revert https://github.com/patrykk/linux-udoo/commit/dd5bf163c1067dace9b172a119fae3c423797ee2 and test it again?
