### ISSUE TITLE
/dev/mxc_vpu does not exist

### ISSUE THREAD

**Issue by fishman** [patrykk/linux-udoo#2]
i'm using the fsl_community repo. and i have /dev/mxc_ipu but no mxc_vpu any idea why?

**Comment by fishman** [comment]
maybe the problem is my uboot  i use uboot-fslc where is that uboot-udoo-2014.10 you talk about?

**Comment by patrykk** [comment]
Hi, We have had this problem since dtsi refactoring. I found where is problem and commited fix.
