### ISSUE TITLE
Could not load galcore kernel module

### ISSUE THREAD

**Issue by chrta** [patrykk/linux-udoo#20]
I get these errors on the udoo quad board:

galcore: Unknown symbol v7_dma_map_area (err 0)
galcore: Unknown symbol v7_dma_flush_range (err 0)

After applying this patch, it works:
https://github.com/Freescale/linux-fslc/commit/22f692548037e39809c32759b5600ee066ef59e9

See also https://lists.yoctoproject.org/pipermail/meta-freescale/2015-August/015595.html

**Comment by patrykk** [comment]
Hi, 
Thanks for your information. Which branch did you test?

**Comment by chrta** [comment]
I tested the current default branch 4.2-5.0.11.p7.1 revision 7cdb9c89af2127cbd27b665b2c92b45805558bb0

**Comment by patrykk** [comment]
I'll merge it

**Comment by patrykk** [comment]
change merged with main branch
