### ISSUE TITLE
Buggy GCC SRA optimization should be disabled

### ISSUE THREAD

**Issue by chrta** [patrykk/linux-udoo#21]
Please pick this commit (relevant if using gcc 4.9 or newer):
https://github.com/Freescale/linux-fslc/commit/fd9af2c0f0b32f7783a0b66c2949932de87ab36f

**Comment by patrykk** [comment]
I have to investigate it.

**Comment by patrykk** [comment]
Is it still problem with 5.3?

**Comment by chrta** [comment]
Yes, the bug is present in 5.3, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65932

**Comment by patrykk** [comment]
It has been incorporated to kernel 4.4. I'll backport to 4.2 branch with driver p4.4
