### ISSUE TITLE
tv restart crashes udoo

### ISSUE THREAD

**Issue by fishman** [patrykk/linux-udoo#3]
when i turn off the tv and turn it back on my udoo crashes. do you have any idea what to look for?

i tried disabling hdmi audio and hdmi cec in the dtsi but so far no luck

**Comment by patrykk** [comment]
Hi, please supply logs and some more information about the case.

**Comment by patrykk** [comment]
How could I reproduce it?

**Comment by patrykk** [comment]
I couldn't reproduce problem.
