### ISSUE TITLE
How To Use FlexCAN

### ISSUE THREAD

**Issue by ctassell** [patrykk/linux-udoo#4]
I'm trying to get a Udoo Dual to work with a CAN shield, and I was wondering if I need to do any patching to this kernel like seems to be required with the stock kernel in order for the device to work?  Also, do I have to do anything on the Arduino side (ie pinMode(60, INPUT);) or will the kernel take care of all of that?

**Comment by patrykk** [comment]
hi, I don't know. Please read udoo documentation. btw. You couldn't use parallely that same pin on sam and imx.

**Comment by patrykk** [comment]
Hi, In any case feel free to reopen ticket.

**Comment by chrta** [comment]
@ctassell Just tested with the current kernel. CAN works out of the box for me. But i configured the connected Arduino pins to inputs to ensure they don't interfere.

**Comment by patrykk** [comment]
Could you create some howto for other users?

**Comment by chrta** [comment]
There are some information in the udoo forum: http://www.udoo.org/forum/threads/can-bus-aka-flex-bus.177/ and http://www.udoo.org/forum/threads/can-bus.1066/
I will add some information on how to get up the can interface running here (plus set up the ip interface, how to send a can message, how to receive a message).
