### ISSUE TITLE
Udoo Cooling Fan Controller.

### ISSUE THREAD

**Issue by moonlinux** [patrykk/linux-udoo#5]
Hi PatyKK,

I appreciate the work you are doing on the UDOO board.
Do you have knowledge on the udoo board support cooling fan.

What are the specification of the cooling fan and how it's controlled.
Can you share some input on this.

-Anand Moon

**Comment by patrykk** [comment]
Hi, Thanks, for now; I don't support fans for udoo. Its a good idea but I have more important issues and not to much free time.
