### ISSUE TITLE
make menuconfig fails

### ISSUE THREAD

**Issue by chrta** [patrykk/linux-udoo#6]
"make menuconfig" fails because of changes done in commit 18453af040af006fc6fa88a7f921bfec63e1f3a5

The folder drivers/staging/media/parport/ and drivers/staging/media/vino do not exist in the 4.0 branch.

**Comment by patrykk** [comment]
Hi, sorry, I have copied Makefiles from wrong kernel tree: 75b57a099598dc0fc4008f91a66bb18756b82ae0 .
