### ISSUE TITLE
analog audio

### ISSUE THREAD

**Issue by DrJulia** [patrykk/linux-udoo#9]
Hello,

Does the analog audio output of the udoo work in the kernel 4.0.0? I am using it with ubuntu 14.04 and I can only see a hdmi sound output.

I know it works with the old kernel:
https://github.com/UDOOboard/Kernel_Unico

**Comment by patrykk** [comment]
Hi, 
Unfortunately no. I don't support vt1613. Maybe in the future. I have very unstable version of the driver but parallely udoo team working on it. You have to wait.

best regards,

**Comment by patrykk** [comment]
first patch: https://github.com/patrykk/linux-udoo/commit/74eef651b929eab0ad2a7ce3b3dff16faac0035b

**Comment by patrykk** [comment]
second patch: https://github.com/patrykk/linux-udoo/commit/def47904be466ef3269c86555708b6371b6b16de

**Comment by patrykk** [comment]
https://github.com/patrykk/linux-udoo/commit/d002c2cc5226e9aebb477be9801f07fba0318c92

**Comment by patrykk** [comment]
https://github.com/patrykk/linux-udoo/commit/c00bc4d584569a168be486efcff0949f0c3e6052

**Comment by patrykk** [comment]
I will merge driver with 4.0 kernel when Udoo team will release 3.14 kernel. It will be soon. Now I have stable and working driver.

**Comment by patrykk** [comment]
Driver released.

**Comment by moonlinux** [comment]
gr8 work. Will you make this driver available in upstream kernel like 4.3

**Comment by patrykk** [comment]
I dont know which branch I'll take next one. Probably 4.2 but I dont know which one will be longterm.
